<?php
// -------------------------------------------------------------------
// This file was automatically generated by the LangBuilder.php script
// Date of creation: 2011/01/26 12:16:11
// -------------------------------------------------------------------
global $lang;


// Output for class or file: OptionalTreeDropdownField
$lang['en_US']['OptionalTreeDropdownField']['NONE'] = 
	'(None)';

// Output for class or file: SitemapModule
$lang['en_US']['SitemapModule']['SITEMAP'] = 
	'Sitemap';
$lang['en_US']['SitemapModule']['INCLUDESITEMAP'] = 
	'Include a sitemap on this page';
$lang['en_US']['SitemapModule']['BASEPAGE'] = 
	'Base page';
$lang['en_US']['SitemapModule']['DEPTH'] = 
	'Depth (0 = unlimited)';
$lang['en_US']['SitemapModule']['SHOWPAGENAME'] = 
	'Show page name';
$lang['en_US']['SitemapModule']['SHOWMETATITLE'] = 
	'Show meta title';
$lang['en_US']['SitemapModule']['SHOWMETADESCRIPTION'] = 
	'Show meta description';
$lang['en_US']['SitemapModule']['SHOWPAGETHUMB'] = 
	'Show page thumbnail';
$lang['en_US']['SitemapModule']['EXCLUDEPAGE'] = 
	'Exclude this page from sitemap';
$lang['en_US']['SitemapModule']['STYLESHEET'] = 
	'Stylesheet';
